### ISSUE TITLE
$scope.tour is not an object

### ISSUE THREAD

**Issue by soniyj** [loringdodge/ionic-tour#1]
Hi, I tried to use your tour but when I tried to run I get an error saying

``` javascript
TypeError: Cannot read property 'start' of undefined
```

It seems that the fromTempleteUrl is not initialised.

I'm using it with Ionic

**Comment by loringdodge** [comment]
Hi Soniyj,

In order for $scope.tour to contain an object if must first be called with fromTemplateUrl which returns a promise. You must then manually attach the provided object to $scope to gain access to the tour methods such as $scope.start().

Try placing this snippet at the top of your controller

```
$ionicTour.fromTemplateUrl('tour-template.html', {
    scope: $scope
  }).then(function(tour){
    $scope.tour = tour;
  });
```

**Comment by soniyj** [comment]
Hi. Thanks for the response but this is what I did. I just put the html into a separate file.

``` javascript
$ionicTour.fromTemplateUrl('templates/example.html', {
    scope: $scope
  }).then(function(tour) {
    console.log("test", tour);
    $scope.tour = tour;
  });
```

It seems that the $scope.tour is not initialised, in fact I put a log just before the $scope.tour but that log is never shown.

**Comment by loringdodge** [comment]
A new tour object should be returned if it successfully retrieves the template. The snippet of code you've included looks accurate and it's likely there's an error being generated so I suggest you include a .catch to identify the error.

```
  $ionicTour.fromTemplateUrl('tour-template.html', {
    scope: $scope
  }).then(function(tour){
    $scope.tour = tour;
  }).
  catch(function(err) {
    console.log(err)
  });
```

And let me know the result.

**Comment by soniyj** [comment]
OK. I will, is the only thing that I didn't try.

**Comment by soniyj** [comment]
Nothing. It seems that the fromTemplateUrl doesn't get call.

``` javascript
$ionicTour.fromTemplateUrl('templates/example.html', {
    scope: $scope
  }).then(function(tour) {
    console.log("AA", tour);
    $scope.tour = tour;
  }).catch(function(err) {
    console.log("EE", err);
  });;

  $scope.start = function() {
    $scope.tour.start({
      autoplay: true
    });
  }

  $scope.start();
```

``` shell
Error: undefined is not an object (evaluating '$scope.tour.start')
```

This is not into the main html or app.js I put this where I need, that is another page that is called sometime while using the app.

**Comment by loringdodge** [comment]
I'll probably need to take a look at the code holistically to further
diagnose the problem. If you're interested, I can pull down your repo and
take a look at it but that depends on your privacy level. Another option is
to recreate this scenario in codepen and modeling after this demo pen
http://codepen.io/loringdodge/pen/epNNgg

**Comment by soniyj** [comment]
Hi @loringdodge, I figured it out which one was the problem. Namely is about time, putting a timeout will solve the issue.

``` javascript
// AngularJS
$timeout(function() {
    $scope.tour.start({
      autoplay: true
    });
  }, 1000);
```

So in this way it's possible to run the tour automatically when the controller starts.

**Comment by loringdodge** [comment]
Awesome. Nice solve. @soniyj

**Comment by soniyj** [comment]
Np :). If you have time, I would like to suggest to put this into the wiki, so people will know how to use this plugin automatically, and in which way they can avoid this small problem.
