### ISSUE TITLE
platforms directory

### ISSUE THREAD

**Issue by theotherphp** [loringdodge/ionic-tour#3]
It appears that the platforms directory contains .o object files for some cordova source files. Is that intentional? Allowing Xcode to build those files alongside the main project creates an invalid bundle for iOS.

**Comment by loringdodge** [comment]
Hey @theotherphp,

That directory was unintentionally added. I've removed it from the git repository. Thanks for noticing.

**Comment by theotherphp** [comment]
Thanks!
